### ISSUE TITLE
None of the bundle engines are supported

### ISSUE THREAD

**Issue by bobjana** [gatehill/imposter-cli#8]
`imposter bundle -t jvm`
produces 
`FATA[0000] JVM engine does not support bundling `

Tested it with the other engine options as well with the same error.

**Comment by outofcoffee** [comment]
Hi @bobjana, thanks for reporting this.

Until recently, only the `awslambda` engine type was supported.

As of [v0.36.0](https://github.com/gatehill/imposter-cli/releases), `docker` is also supported.

**Comment by outofcoffee** [comment]
Docs here: https://docs.imposter.sh/bundle/#docker-bundles
